id: t5_generative_small
title: "T5 generative trained on MS-Marco (debug)"
description: |
    This model has been trained on MsMarco v1 but only a few iterations (debug)

gpu: true
base: "t5-small"
decoder_outdim: 4
max_depth: 2
dev_test_size: 50

validation:
    size: 10

indexation:
    requirements: duration=2 days & cpu(mem=4G)

retrieval:
    requirements: duration=2 days & cuda(mem=8G)
    k: 20

monobert:
    optimization:
        scheduler: false
        steps_per_epoch: 1000
        max_epochs: 100
        batch_size: 64
        eps: 1.0e-6
        lr: 5.0e-5
        re_no_l2_regularization:
          - "\\.layer_norm\\."
          - "\\.final_layer_norm\\."

    sample_max: 16

    validation_interval: 500
    validation_top_k: 20
    requirements: duration=2 days & cuda(mem=24G)
