id: t5_generative
title: t5 generative trained on MS-MARCO
description: |
    This model has been trained on MsMarco v1

gpu: true
base: 't5-base'

preprocessing:
    requirements: duration=6h & cpu(mem=4G, cores=8)

indexation:
    requirements: duration=6h & cpu(mem=4G, cores=8)

validation:
    # Use 500 topics for validation
    size: 500

monobert:
    optimization:
        steps_per_epoch: 100
        batch_size: 64
        max_epochs: 1000
        num_warmup_steps: 10000
        warmup_min_factor: 0
        weight_decay: 0.01
        lr: 3.0e-6
        eps: 1.0e-6
        re_no_l2_regularization:
          - "\\.layer_norm\\."
          - "\\.final_layer_norm\\."

    validation_interval: 20
    requirements: duration=6 days & cuda(mem=40G)


retrieval:
    requirements: duration=4 days & cuda(mem=24G)
    k: 1000
