id: t5_generative
title: t5 generative trained on MS-MARCO
description: |
    This model has been trained on MsMarco v1

gpu: true
base: 't5-small'
decoder_outdim: 10
max_depth: 7
alpha: 0.1

preprocessing:
    requirements: duration=6h & cpu(mem=4G, cores=8)

indexation:
    requirements: duration=6h & cpu(mem=4G, cores=8)

validation:
    # Use 500 topics for validation
    size: 500

monobert:
    optimization:
        steps_per_epoch: 100
        batch_size: 128
        max_epochs: 3000
        num_warmup_steps: 30000
        warmup_min_factor: 0
        weight_decay: 0.01
        lr: 2.0e-5
        eps: 1.0e-8
        re_no_l2_regularization:
          - "\\.layer_norm\\."
          - "\\.final_layer_norm\\."

    validation_interval: 100
    requirements: duration=8 days & cuda(mem=40G)


retrieval:
    requirements: duration=4 days & cuda(mem=24G)
    k: 1000
