id: monobert
title: "monoBERT trained on MS-Marco"
description: |
    Passage Re-ranking with BERT (Rodrigo Nogueira, Kyunghyun Cho). 2019.
    https://arxiv.org/abs/1901.04085

    This model has been trained on MsMarco v1

gpu: true
indexation:
    requirements: duration=6 days & cpu(mem=4G, cores=8)

validation_size: 500

monobert:
    steps_per_epoch: 32
    validation_interval: 32
    batch_size: 64
    max_epochs: 3200
    num_warmup_steps: 10000
    warmup_min_factor: 0
    lr: 3.0e-6
    requirements: duration=4 days & cuda(mem=24G) * 2

retrieval:
    requirements: duration=2 days & cuda(mem=24G)
    k: 1000
