type: splade-small
Launcher:
    gpu: true
    tags: []
Indexation:
    requirements: duration=2 days & cpu(mem=2G)
    training_requirements: duration=2 days & cuda(mem=24G)
Learner:
    validation_size: 10
    # validation for each (steps_per_epoch * validation interval) steps
    steps_per_epoch: 128
    validation_interval: 1
    splade_batch_size: 48
    max_epochs: 4
    num_warmup_steps: 20
    early_stop: 0
    lr: 2.0e-5
    min_lambda_q: 3.0e-4
    min_lambda_d: 1.0e-4
    lambda_q: 3.0e-1
    lambda_d: 1.0e-1
    lamdba_warmup_steps: 300
    requirements: duration=2 days & cuda(mem=8G)
Evaluation:
    requirements: duration=2 days & cuda(mem=8G)
base_retriever:
    topK: 20
tas_balance_retriever:
    retTopK: 10
    # See FAISS guidelines
    # https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index
    # TREC COVID has 192509 documents
    # K within 4*sqrt(N) to 16*sqrt(N)
    indexspec: OPQ4_16,IVF2048_HNSW32,PQ4
    # 30*K and 256*K
    faiss_max_traindocs:  65_536
full_retriever:
    batch_size_full_retriever: 20
